services:
  postgres:
    image: postgres:16-alpine
    container_name: mood_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - mood_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Development service
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mood_web_dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      INVITATION_KEY: ${INVITATION_KEY}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      NODE_ENV: development
    ports:
      - "3000:3000"
    networks:
      - mood_network
    depends_on:
      postgres:
        condition: service_healthy

  # Production service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mood_web_prod
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      INVITATION_KEY: ${INVITATION_KEY}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    ports:
      - "3000:3000"
    networks:
      - mood_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  mood_network:
    driver: bridge
